services:
  dd-f:
    container_name: dd_front
    image: ddokddak/front
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/log/nginx:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: always
networks:
  default:
    external:
      name: dd