name: React CI with Docker
on:
  push:
    branches: dev
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 도커허브 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 도커 이미지 빌드/업로드
      - name: docker image build and push
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}/front -f Dockerfile.prod .
          docker push ${{ secrets.DOCKER_REPO }}/front